import mongoose from 'mongoose';

const TimeLogSchema = new mongoose.Schema({
    timeSpent : Number ,//time added in this entry
    date : {type :Date, default : Date.now()} //when this time was added
})

const TaskSchema = new mongoose.Schema({
    userId:{
        //1. mongoose.Schema.Types.ObjectId represents a unique identifier for documents in mongodb
        //2. It is a 12-byte hexadecimal string , automatically generated by mongodb if not provided
        //3. it is mainly used for referencing other documents(i.e. eastablishing relationships)
        type:mongoose.Schema.Types.ObjectId,
        ref:'User', //Reference to the 'User' model
        required:true, //when this time was added
    },
    task:{
        type:String,
        required:true,
    },
    totalTime:{
        type:Number,
        required:true,
    }, // total cumulative time 
    timeLogs:[TimeLogSchema]//stores time logs for filtering later
})


export default mongoose.model('Tasks',TaskSchema,'journal-collections');
